os: osx
language: node_js
node_js:
    - "12"
services:
    - xvfb
#dist: trusty
before_script:
    - "export DISPLAY=:99.0"
    - "sh -e /etc/init.d/xvfb start"
    - sleep 3 # give xvfb some time to start
sudo: required
addons:
    chrome: stable
before_install:
    - "/Applications/Google\\ Chrome.app/Contents/MacOS/Google\\ Chrome --headless --disable-gpu --remote-debugging-port=9222 http://localhost &"
script:
    - xvfb-run npm test