language: node_js
node_js:
    - node
services:
    - xvfb
dist: xenial
addons:
    chrome: stable
before_install:
    - # start your web application and listen on `localhost`
    - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &
script: 
    - xvfb-run npm test